spring.application.name=billingsoftware
# Server port
server.port=8080

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/billing_db
spring.datasource.username=root
spring.datasource.password=himanshu@2004

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Shop Details (constant info for every bill)
shop.name=Sachin Auto Spares
shop.address=Bhigwan Chowk, Baramati
shop.gstin=27ADLPG0927A1Z0
shop.phone=9890133799

# GST rates
cgst.rate=9
sgst.rate=9
